### ISSUE TITLE
Cannot use edit mode in CLion in a devcontainer with a working set

### ISSUE THREAD

**Issue by rafaelBauer** [microsoft/copilot-intellij-feedback#323]
Hello,

I tried to use the GitHub Copilot in Edit mode with files in the "Working set" I am getting an error:
`An error occured while processing your request. Please try again later.`

I also tried to use it without any "Working set" files. I didn't get the error, but it would create new files in the a wrong location:
`~/.config/JetBrains/CLion2025.1/projects/3c02817e3111dd8425e5ddca6265768e3edca8e8/.github`

I did the setup of the devcontainer in a docker-compose file, where I set the working directory to the directory of the repo by using the env variable $PWD, and bind some `/home/${USER}` paths needed. The binds are:
```
    working_dir: ${PWD:?error}
    volumes:
      - type: bind
        source: .
        target: ${PWD:?error}
        read_only: false

      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true

      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true

      # Potentially not needed, but just to be safe
      - type: bind
        source: /home/${USER:?error}/.config/JetBrains/
        target: /home/${USER:?error}/.config/JetBrains/
        read_only: false

      - type: bind
        source: /home/${USER:?error}/.config/
        target: /home/${USER:?error}/.config/
        read_only: false
```

### Steps to Reproduce:

1. Open the devcontainer that binds the project files to the same location as the host (not a copy)
2. Open GitHub Copilot in edit mode
3. Add project files to the working set
4. Send any prompt.

### Screenshots/Recording:

![Image](https://github.com/user-attachments/assets/9948aee2-01ec-4bf2-8ce2-44a2121b7508)

The output of the "About" in CLion is:
```
CLion 2025.1.2
Build #JBC-251.26094.123, built on June 3, 2025
Source revision: f0f8b9f8a6ab5
Runtime version: 21.0.7+9-b895.130 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-59-generic
Ubuntu 22.04.5 LTS; glibc: 2.35
Controller in Remote Development
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  cache.folding.model.on.disk=false
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.github.colorscheme (251.23774.318)
  com.intellij.plugins.monokai.colorscheme (251.23774.318)
  com.intellij.plugins.twilight.colorscheme (251.23774.318)
  com.intellij.plugins.cobalt.colorscheme (251.23774.318)
  com.intellij.plugins.vibrantink.colorscheme (251.23774.318)
  com.intellij.plugins.espresso.colorscheme (251.23774.318)
  com.intellij.plugins.all_hallows_eve.colorscheme (251.23774.318)
  com.intellij.plugins.warmneon.colorscheme (251.23774.318)
  com.intellij.plugins.rails_casts.colorscheme (251.23774.318)
  com.intellij.plugins.xcode.colorscheme (251.23774.318)
  com.intellij.plugins.dawm.colorscheme (251.23774.318)
  com.github.copilot (1.5.46-243)
  com.intellij.plugins.blackboard.colorscheme (251.23774.318)
Current Desktop: ubuntu:GNOME
```
